# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/mainwindow.ui'
#
# Created: Mon Apr 24 17:12:39 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(503, 158)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../../Bilder/Design/tsicons/admin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.info = QtGui.QHBoxLayout()
        self.info.setObjectName("info")
        self.playing = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playing.sizePolicy().hasHeightForWidth())
        self.playing.setSizePolicy(sizePolicy)
        self.playing.setMinimumSize(QtCore.QSize(60, 20))
        self.playing.setObjectName("playing")
        self.info.addWidget(self.playing)
        self.title = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        self.title.setMinimumSize(QtCore.QSize(0, 20))
        self.title.setObjectName("title")
        self.info.addWidget(self.title)
        self.by = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.by.sizePolicy().hasHeightForWidth())
        self.by.setSizePolicy(sizePolicy)
        self.by.setMinimumSize(QtCore.QSize(20, 20))
        self.by.setObjectName("by")
        self.info.addWidget(self.by)
        self.interpret = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interpret.sizePolicy().hasHeightForWidth())
        self.interpret.setSizePolicy(sizePolicy)
        self.interpret.setMinimumSize(QtCore.QSize(0, 20))
        self.interpret.setObjectName("interpret")
        self.info.addWidget(self.interpret)
        self.gridLayout.addLayout(self.info, 1, 0, 1, 1)
        self.buttons = QtGui.QHBoxLayout()
        self.buttons.setObjectName("buttons")
        self.previous = QtGui.QPushButton(self.centralwidget)
        self.previous.setCursor(QtCore.Qt.PointingHandCursor)
        self.previous.setObjectName("previous")
        self.buttons.addWidget(self.previous)
        self.play = QtGui.QPushButton(self.centralwidget)
        self.play.setCursor(QtCore.Qt.PointingHandCursor)
        self.play.setObjectName("play")
        self.buttons.addWidget(self.play)
        self.next = QtGui.QPushButton(self.centralwidget)
        self.next.setCursor(QtCore.Qt.PointingHandCursor)
        self.next.setObjectName("next")
        self.buttons.addWidget(self.next)
        self.gridLayout.addLayout(self.buttons, 2, 0, 1, 1)
        self.time = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time.sizePolicy().hasHeightForWidth())
        self.time.setSizePolicy(sizePolicy)
        self.time.setMinimumSize(QtCore.QSize(0, 20))
        self.time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.time.setAlignment(QtCore.Qt.AlignCenter)
        self.time.setObjectName("time")
        self.gridLayout.addWidget(self.time, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 503, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "SewPlayer", None, QtGui.QApplication.UnicodeUTF8))
        self.playing.setText(QtGui.QApplication.translate("MainWindow", "Playing: ", None, QtGui.QApplication.UnicodeUTF8))
        self.title.setText(QtGui.QApplication.translate("MainWindow", "Untitled", None, QtGui.QApplication.UnicodeUTF8))
        self.by.setText(QtGui.QApplication.translate("MainWindow", "by", None, QtGui.QApplication.UnicodeUTF8))
        self.interpret.setText(QtGui.QApplication.translate("MainWindow", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.previous.setText(QtGui.QApplication.translate("MainWindow", "Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.play.setText(QtGui.QApplication.translate("MainWindow", "Play / Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.next.setText(QtGui.QApplication.translate("MainWindow", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.time.setText(QtGui.QApplication.translate("MainWindow", "00:00:00 - 00:00:00", None, QtGui.QApplication.UnicodeUTF8))

