from PySide import QtGui

from view.ui.ng import Ui_MainWindow


class MainWindow(QtGui.QMainWindow, Ui_MainWindow):
    def __init__(self):
        """
        Inherits from Ui_MainWindow generated by PySide
        """
        super(MainWindow, self).__init__()
        self.setupUi(self)


class View:
    def __init__(self):
        """
        Instantiate a MainWindow and shows it
        """
        self.frame = MainWindow()
        self.frame.show()

    def set_time(self, time):
        """
        Sets time label to given parameter

        :param time: int, float, str
        """
        self.frame.time.setText(str(time))

    def set_score(self, score):
        """
        Sets score label to given parameter

        :param score: int, float, str
        """
        self.frame.score.setText(str(score))

    def set_number(self, number):
        """
        Sets number label to given parameter

        :param number: int, float, str
        """
        self.frame.number.setText(str(number))

    def set_fails(self, fails):
        """
        Sets fails label to given parameter

        :param fails: int, float, str
        """
        self.frame.fails.setText(str(fails))

    def set_streak(self, streak):
        """
        Sets streak label to given parameter

        :param streak: int, float, str
        """
        self.frame.streak.setText(str(streak))
